// <auto-generated />
namespace StudentTrackingSystem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Graduation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Graduation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710280045242_Graduation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
