namespace StudentTrackingSystem3.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangeTableName : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.G_Activity", newName: "Activity");
            RenameTable(name: "dbo.G_CurriculumVitae", newName: "CurriculumVitae");
            RenameTable(name: "dbo.G_Student", newName: "Student");
            RenameTable(name: "dbo.G_CommitteeMember", newName: "CommitteeMember");
            RenameTable(name: "dbo.G_Coursework", newName: "Coursework");
            RenameTable(name: "dbo.G_Course", newName: "Course");
            RenameTable(name: "dbo.G_CommonFields", newName: "CommonFields");
            RenameTable(name: "dbo.G_Performance", newName: "Performance");
            RenameTable(name: "dbo.G_Graduation", newName: "Graduation");
            RenameTable(name: "dbo.G_PostGraduation", newName: "PostGraduation");
            RenameTable(name: "dbo.G_PrevDegree", newName: "PrevDegree");
            RenameTable(name: "dbo.G_PreviousEmployment", newName: "PreviousEmployment");
            RenameTable(name: "dbo.G_Grants", newName: "Grants");
            RenameTable(name: "dbo.G_Honors", newName: "Honors");
            RenameTable(name: "dbo.G_Publications", newName: "Publications");
            RenameTable(name: "dbo.G_PersonRaces", newName: "PersonRaces");
            RenameTable(name: "dbo.G_Races", newName: "Races");
            RenameTable(name: "dbo.G_File", newName: "File");
            RenameTable(name: "dbo.G_Manuscript", newName: "Manuscript");
            DropIndex("dbo.File", new[] { "ActivityID" });
            RenameColumn(table: "dbo.File", name: "CurriculumVitaeID", newName: "__mig_tmp__0");
            RenameColumn(table: "dbo.Performance", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID1", newName: "CommonFields_ID1");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID1", newName: "CommonFields_ID1");
            RenameColumn(table: "dbo.PreviousEmployment", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID2", newName: "CommonFields_ID2");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID3", newName: "CommonFields_ID3");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID4", newName: "CommonFields_ID4");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID5", newName: "CommonFields_ID5");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID6", newName: "CommonFields_ID6");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID2", newName: "CommonFields_ID2");
            RenameColumn(table: "dbo.Coursework", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Grants", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID3", newName: "CommonFields_ID3");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID4", newName: "CommonFields_ID4");
            RenameColumn(table: "dbo.Performance", name: "G_CommonFields_ID1", newName: "CommonFields_ID1");
            RenameColumn(table: "dbo.Performance", name: "G_CommonFields_ID2", newName: "CommonFields_ID2");
            RenameColumn(table: "dbo.Publications", name: "G_CommonFields_ID", newName: "CommonFields_ID");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID7", newName: "CommonFields_ID7");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID8", newName: "CommonFields_ID8");
            RenameColumn(table: "dbo.Graduation", name: "G_CommonFields_ID9", newName: "CommonFields_ID9");
            RenameColumn(table: "dbo.Coursework", name: "G_CommonFields_ID1", newName: "CommonFields_ID1");
            RenameColumn(table: "dbo.PreviousEmployment", name: "G_CommonFields_ID1", newName: "CommonFields_ID1");
            RenameColumn(table: "dbo.Performance", name: "G_CommonFields_ID3", newName: "CommonFields_ID3");
            RenameColumn(table: "dbo.Student", name: "G_CommonFields_ID5", newName: "CommonFields_ID5");
            RenameColumn(table: "dbo.File", name: "ManuscriptID", newName: "CurriculumVitaeId");
            RenameColumn(table: "dbo.File", name: "__mig_tmp__0", newName: "ManuscriptId");
            RenameIndex(table: "dbo.File", name: "IX_CurriculumVitaeID", newName: "__mig_tmp__0");
            RenameIndex(table: "dbo.File", name: "IX_ManuscriptID", newName: "IX_CurriculumVitaeId");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID1", newName: "IX_CommonFields_ID1");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID2", newName: "IX_CommonFields_ID2");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID3", newName: "IX_CommonFields_ID3");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID4", newName: "IX_CommonFields_ID4");
            RenameIndex(table: "dbo.Student", name: "IX_G_CommonFields_ID5", newName: "IX_CommonFields_ID5");
            RenameIndex(table: "dbo.Coursework", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.Coursework", name: "IX_G_CommonFields_ID1", newName: "IX_CommonFields_ID1");
            RenameIndex(table: "dbo.Performance", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.Performance", name: "IX_G_CommonFields_ID1", newName: "IX_CommonFields_ID1");
            RenameIndex(table: "dbo.Performance", name: "IX_G_CommonFields_ID2", newName: "IX_CommonFields_ID2");
            RenameIndex(table: "dbo.Performance", name: "IX_G_CommonFields_ID3", newName: "IX_CommonFields_ID3");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID1", newName: "IX_CommonFields_ID1");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID2", newName: "IX_CommonFields_ID2");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID3", newName: "IX_CommonFields_ID3");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID4", newName: "IX_CommonFields_ID4");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID5", newName: "IX_CommonFields_ID5");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID6", newName: "IX_CommonFields_ID6");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID7", newName: "IX_CommonFields_ID7");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID8", newName: "IX_CommonFields_ID8");
            RenameIndex(table: "dbo.Graduation", name: "IX_G_CommonFields_ID9", newName: "IX_CommonFields_ID9");
            RenameIndex(table: "dbo.PreviousEmployment", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.PreviousEmployment", name: "IX_G_CommonFields_ID1", newName: "IX_CommonFields_ID1");
            RenameIndex(table: "dbo.Grants", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.Publications", name: "IX_G_CommonFields_ID", newName: "IX_CommonFields_ID");
            RenameIndex(table: "dbo.File", name: "__mig_tmp__0", newName: "IX_ManuscriptId");
            DropPrimaryKey("dbo.File");
            DropColumn("dbo.File", "G_FileId");
            AddColumn("dbo.File", "FileId", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.File", "FileId");
            CreateIndex("dbo.File", "ActivityId");
            
        }
        
        public override void Down()
        {
            DropIndex("dbo.File", new[] { "ActivityId" });
            DropPrimaryKey("dbo.File");
            DropColumn("dbo.File", "FileId");
            AddColumn("dbo.File", "G_FileId", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.File", "G_FileId");
            RenameIndex(table: "dbo.File", name: "IX_ManuscriptId", newName: "__mig_tmp__0");
            RenameIndex(table: "dbo.Publications", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.Grants", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.PreviousEmployment", name: "IX_CommonFields_ID1", newName: "IX_G_CommonFields_ID1");
            RenameIndex(table: "dbo.PreviousEmployment", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID9", newName: "IX_G_CommonFields_ID9");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID8", newName: "IX_G_CommonFields_ID8");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID7", newName: "IX_G_CommonFields_ID7");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID6", newName: "IX_G_CommonFields_ID6");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID5", newName: "IX_G_CommonFields_ID5");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID4", newName: "IX_G_CommonFields_ID4");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID3", newName: "IX_G_CommonFields_ID3");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID2", newName: "IX_G_CommonFields_ID2");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID1", newName: "IX_G_CommonFields_ID1");
            RenameIndex(table: "dbo.Graduation", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.Performance", name: "IX_CommonFields_ID3", newName: "IX_G_CommonFields_ID3");
            RenameIndex(table: "dbo.Performance", name: "IX_CommonFields_ID2", newName: "IX_G_CommonFields_ID2");
            RenameIndex(table: "dbo.Performance", name: "IX_CommonFields_ID1", newName: "IX_G_CommonFields_ID1");
            RenameIndex(table: "dbo.Performance", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.Coursework", name: "IX_CommonFields_ID1", newName: "IX_G_CommonFields_ID1");
            RenameIndex(table: "dbo.Coursework", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID5", newName: "IX_G_CommonFields_ID5");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID4", newName: "IX_G_CommonFields_ID4");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID3", newName: "IX_G_CommonFields_ID3");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID2", newName: "IX_G_CommonFields_ID2");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID1", newName: "IX_G_CommonFields_ID1");
            RenameIndex(table: "dbo.Student", name: "IX_CommonFields_ID", newName: "IX_G_CommonFields_ID");
            RenameIndex(table: "dbo.File", name: "IX_CurriculumVitaeId", newName: "IX_ManuscriptID");
            RenameIndex(table: "dbo.File", name: "__mig_tmp__0", newName: "IX_CurriculumVitaeID");
            RenameColumn(table: "dbo.File", name: "ManuscriptId", newName: "__mig_tmp__0");
            RenameColumn(table: "dbo.File", name: "CurriculumVitaeId", newName: "ManuscriptID");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID5", newName: "G_CommonFields_ID5");
            RenameColumn(table: "dbo.Performance", name: "CommonFields_ID3", newName: "G_CommonFields_ID3");
            RenameColumn(table: "dbo.PreviousEmployment", name: "CommonFields_ID1", newName: "G_CommonFields_ID1");
            RenameColumn(table: "dbo.Coursework", name: "CommonFields_ID1", newName: "G_CommonFields_ID1");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID9", newName: "G_CommonFields_ID9");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID8", newName: "G_CommonFields_ID8");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID7", newName: "G_CommonFields_ID7");
            RenameColumn(table: "dbo.Publications", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Performance", name: "CommonFields_ID2", newName: "G_CommonFields_ID2");
            RenameColumn(table: "dbo.Performance", name: "CommonFields_ID1", newName: "G_CommonFields_ID1");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID4", newName: "G_CommonFields_ID4");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID3", newName: "G_CommonFields_ID3");
            RenameColumn(table: "dbo.Grants", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Coursework", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID2", newName: "G_CommonFields_ID2");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID6", newName: "G_CommonFields_ID6");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID5", newName: "G_CommonFields_ID5");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID4", newName: "G_CommonFields_ID4");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID3", newName: "G_CommonFields_ID3");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID2", newName: "G_CommonFields_ID2");
            RenameColumn(table: "dbo.PreviousEmployment", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID1", newName: "G_CommonFields_ID1");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID1", newName: "G_CommonFields_ID1");
            RenameColumn(table: "dbo.Student", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Graduation", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.Performance", name: "CommonFields_ID", newName: "G_CommonFields_ID");
            RenameColumn(table: "dbo.File", name: "__mig_tmp__0", newName: "CurriculumVitaeID");
            CreateIndex("dbo.File", "ActivityID");
            RenameTable(name: "dbo.Manuscript", newName: "G_Manuscript");
            RenameTable(name: "dbo.File", newName: "G_File");
            RenameTable(name: "dbo.Races", newName: "G_Races");
            RenameTable(name: "dbo.PersonRaces", newName: "G_PersonRaces");
            RenameTable(name: "dbo.Publications", newName: "G_Publications");
            RenameTable(name: "dbo.Honors", newName: "G_Honors");
            RenameTable(name: "dbo.Grants", newName: "G_Grants");
            RenameTable(name: "dbo.PreviousEmployment", newName: "G_PreviousEmployment");
            RenameTable(name: "dbo.PrevDegree", newName: "G_PrevDegree");
            RenameTable(name: "dbo.PostGraduation", newName: "G_PostGraduation");
            RenameTable(name: "dbo.Graduation", newName: "G_Graduation");
            RenameTable(name: "dbo.Performance", newName: "G_Performance");
            RenameTable(name: "dbo.CommonFields", newName: "G_CommonFields");
            RenameTable(name: "dbo.Course", newName: "G_Course");
            RenameTable(name: "dbo.Coursework", newName: "G_Coursework");
            RenameTable(name: "dbo.CommitteeMember", newName: "G_CommitteeMember");
            RenameTable(name: "dbo.Student", newName: "G_Student");
            RenameTable(name: "dbo.CurriculumVitae", newName: "G_CurriculumVitae");
            RenameTable(name: "dbo.Activity", newName: "G_Activity");
        }
    }
}
