//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Courseworks = new HashSet<Coursework>();
        }
    
        public int ID { get; set; }
        public int Credits { get; set; }
        public string CourseNum { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseTrackID { get; set; }
        public Nullable<int> CoursePlanID { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coursework> Courseworks { get; set; }
    }
}
