//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeProgram
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int GraduationID { get; set; }
        public int DegreeProgramTypeId { get; set; }
        public int DegreeStartYear { get; set; }
        public int DegreeStartSemsId { get; set; }
        public int PlansId { get; set; }
        public int TracksId { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual CommonField CommonField2 { get; set; }
        public virtual CommonField CommonField3 { get; set; }
        public virtual Graduation Graduation { get; set; }
        public virtual Student Student { get; set; }
    }
}
