//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public int FileType { get; set; }
        public Nullable<int> ManuscriptId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> CurriculumVitaeId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual CurriculumVitae CurriculumVitae { get; set; }
        public virtual Manuscript Manuscript { get; set; }
    }
}
