//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduation()
        {
            this.DegreePrograms = new HashSet<DegreeProgram>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> DegreeEndSemsId { get; set; }
        public Nullable<int> DegreeEndYear { get; set; }
        public Nullable<int> QualifierResultId { get; set; }
        public Nullable<int> Qualifier2ResultId { get; set; }
        public Nullable<System.DateTime> DateOfQualification { get; set; }
        public Nullable<System.DateTime> DateOfQualification2 { get; set; }
        public string Form2Title { get; set; }
        public Nullable<System.DateTime> Form2Date { get; set; }
        public Nullable<int> Form2ResultId { get; set; }
        public Nullable<int> CompExamResultId { get; set; }
        public Nullable<System.DateTime> DateOfCompExam { get; set; }
        public Nullable<int> CompExam2ResultId { get; set; }
        public Nullable<System.DateTime> DateOfCompExam2 { get; set; }
        public string AdvisorName { get; set; }
        public string AdvisorEmail { get; set; }
        public string AdvisorDepartment { get; set; }
        public string AdvisorUniversity { get; set; }
        public string Form3Title { get; set; }
        public Nullable<System.DateTime> Form3Date { get; set; }
        public Nullable<int> Form3ResultId { get; set; }
        public Nullable<int> FinalExamResultId { get; set; }
        public Nullable<System.DateTime> DateOfFinalExam { get; set; }
        public Nullable<int> FinalExam2ResultId { get; set; }
        public Nullable<System.DateTime> DateOfFinalExam2 { get; set; }
        public Nullable<int> Form2Type_ID { get; set; }
        public Nullable<int> TakenQHS601Id { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual CommonField CommonField2 { get; set; }
        public virtual CommonField CommonField3 { get; set; }
        public virtual CommonField CommonField4 { get; set; }
        public virtual CommonField CommonField5 { get; set; }
        public virtual CommonField CommonField6 { get; set; }
        public virtual CommonField CommonField7 { get; set; }
        public virtual CommonField CommonField8 { get; set; }
        public virtual CommonField CommonField9 { get; set; }
        public virtual CommonField CommonField10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DegreeProgram> DegreePrograms { get; set; }
        public virtual Student Student { get; set; }
    }
}
