//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string GrantInformation { get; set; }
        public int GrantMonthId { get; set; }
        public int GrantYear { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual Student Student { get; set; }
    }
}
