//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int CategoryID { get; set; }
        public string CategoryInfo { get; set; }
        public Nullable<int> PublicationStatsID { get; set; }
        public Nullable<int> AbstractStatsID { get; set; }
        public Nullable<int> ProposalStatsID { get; set; }
        public Nullable<int> TeachingStatsID { get; set; }
        public Nullable<int> CommonFields_ID { get; set; }
        public Nullable<int> CommonFields_ID1 { get; set; }
        public Nullable<int> CommonFields_ID2 { get; set; }
        public Nullable<int> CommonFields_ID3 { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual CommonField CommonField2 { get; set; }
        public virtual CommonField CommonField3 { get; set; }
        public virtual CommonField CommonField4 { get; set; }
        public virtual CommonField CommonField5 { get; set; }
        public virtual CommonField CommonField6 { get; set; }
        public virtual CommonField CommonField7 { get; set; }
        public virtual CommonField CommonField8 { get; set; }
        public virtual Student Student { get; set; }
    }
}
