//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRace
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int RaceID { get; set; }
        public bool IsSelectedPR { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Student Student { get; set; }
    }
}
