//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousEmployment
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string Position { get; set; }
        public string Employer { get; set; }
        public int StartMonthId { get; set; }
        public int StartYear { get; set; }
        public int EndMonthId { get; set; }
        public int EndYear { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
