//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevDegree
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int DegreeTypesID { get; set; }
        public string Title { get; set; }
        public decimal CumulativeGPA { get; set; }
        public string SchoolName { get; set; }
        public string Major { get; set; }
        public string SecondMajor { get; set; }
        public string Minor { get; set; }
        public System.DateTime DateOfAward { get; set; }
    
        public virtual CommonField CommonField { get; set; }
        public virtual Student Student { get; set; }
    }
}
