//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolContext2Entities : DbContext
    {
        public SchoolContext2Entities()
            : base("name=SchoolContext2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CommitteeMember> CommitteeMembers { get; set; }
        public virtual DbSet<CommonField> CommonFields { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Coursework> Courseworks { get; set; }
        public virtual DbSet<CurriculumVitae> CurriculumVitaes { get; set; }
        public virtual DbSet<DegreeProgram> DegreePrograms { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Graduation> Graduations { get; set; }
        public virtual DbSet<Grant> Grants { get; set; }
        public virtual DbSet<Honor> Honors { get; set; }
        public virtual DbSet<Manuscript> Manuscripts { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<PersonRace> PersonRaces { get; set; }
        public virtual DbSet<PostGraduation> PostGraduations { get; set; }
        public virtual DbSet<PrevDegree> PrevDegrees { get; set; }
        public virtual DbSet<PreviousEmployment> PreviousEmployments { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
