//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Activities = new HashSet<Activity>();
            this.CommitteeMembers = new HashSet<CommitteeMember>();
            this.Courseworks = new HashSet<Coursework>();
            this.CurriculumVitaes = new HashSet<CurriculumVitae>();
            this.DegreePrograms = new HashSet<DegreeProgram>();
            this.Graduations = new HashSet<Graduation>();
            this.Grants = new HashSet<Grant>();
            this.Honors = new HashSet<Honor>();
            this.Manuscripts = new HashSet<Manuscript>();
            this.Performances = new HashSet<Performance>();
            this.PersonRaces = new HashSet<PersonRace>();
            this.PostGraduations = new HashSet<PostGraduation>();
            this.PrevDegrees = new HashSet<PrevDegree>();
            this.PreviousEmployments = new HashSet<PreviousEmployment>();
            this.Publications = new HashSet<Publication>();
        }
    
        public int Id { get; set; }
        public int StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SchoolEmail { get; set; }
        public string OtherEmail { get; set; }
        public string Phone { get; set; }
        public int GendersId { get; set; }
        public string RaceOther { get; set; }
        public int CitizenshipStatsId { get; set; }
        public int EmploymentStatsId { get; set; }
        public Nullable<int> InterimAdvisorsId { get; set; }
        public Nullable<int> PermanentAdvisorsId { get; set; }
        public string RaceAsianOther { get; set; }
        public string RacePacIsleOther { get; set; }
        public string EmploymentStatsOther { get; set; }
        public string PermanentAdvisorOther { get; set; }
        public Nullable<int> Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeMember> CommitteeMembers { get; set; }
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual CommonField CommonField2 { get; set; }
        public virtual CommonField CommonField3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coursework> Courseworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumVitae> CurriculumVitaes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DegreeProgram> DegreePrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduation> Graduations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grant> Grants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Honor> Honors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manuscript> Manuscripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRace> PersonRaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostGraduation> PostGraduations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrevDegree> PrevDegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreviousEmployment> PreviousEmployments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }
    }
}
