//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Activities = new HashSet<Activity>();
            this.CommitteeMembers = new HashSet<CommitteeMember>();
            this.Courseworks = new HashSet<Coursework>();
            this.CurriculumVitaes = new HashSet<CurriculumVitae>();
            this.DegreePrograms = new HashSet<DegreeProgram>();
            this.Graduations = new HashSet<Graduation>();
            this.Grants = new HashSet<Grant>();
            this.Honors = new HashSet<Honor>();
            this.Manuscripts = new HashSet<Manuscript>();
            this.Performances = new HashSet<Performance>();
            this.PersonRaces = new HashSet<PersonRace>();
            this.PostGraduations = new HashSet<PostGraduation>();
            this.PrevDegrees = new HashSet<PrevDegree>();
            this.PreviousEmployments = new HashSet<PreviousEmployment>();
            this.Publications = new HashSet<Publication>();
        }
    
        public int Id { get; set; }
        public int StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SchoolEmail { get; set; }
        public string OtherEmail { get; set; }
        public string Phone { get; set; }
        public int GendersId { get; set; }
        public string RaceOther { get; set; }
        public int CitizenshipStatsId { get; set; }
        public int EmploymentStatsId { get; set; }
        public Nullable<int> InterimAdvisorsId { get; set; }
        public Nullable<int> PermanentAdvisorsId { get; set; }
        public string RaceAsianOther { get; set; }
        public string RacePacIsleOther { get; set; }
        public string EmploymentStatsOther { get; set; }
        public string PermanentAdvisorOther { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> JabsomOrientationId { get; set; }
        public Nullable<int> DqhsOrientationId { get; set; }
        public Nullable<int> DayExtensionId { get; set; }
        public Nullable<int> CourseRegFallSemId { get; set; }
        public string PermanentAdvisorOtherName { get; set; }
        public Nullable<System.DateTime> PermanentAdvisorFirstMeetingDate { get; set; }
        public Nullable<int> JabsomAccessCardId { get; set; }
        public string Notes { get; set; }
        public string InterimAdvisorOtherName { get; set; }
        public Nullable<int> InterimAdvisorCategoryId { get; set; }
        public string InterimAdvisorDepartment { get; set; }
        public string InterimAdvisorCategoryOther { get; set; }
        public Nullable<bool> IsGradAssistantship { get; set; }
        public Nullable<System.DateTime> DegreeStartDate { get; set; }
        public Nullable<System.DateTime> DegreeEndDate { get; set; }
        public string CitizenshipStatsOther { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> UhmEvalFormId { get; set; }
        public Nullable<int> PersonalStatementId { get; set; }
        public Nullable<int> CvOrResumeId { get; set; }
        public Nullable<int> TranscriptId { get; set; }
        public Nullable<int> ReferencesCountId { get; set; }
        public Nullable<int> GradSchoolEntranceExamId { get; set; }
        public string GradSchoolEntranceExamOther { get; set; }
        public Nullable<int> EnglishProficiencyExamId { get; set; }
        public Nullable<int> StatusAcceptedId { get; set; }
        public Nullable<int> AdmissionLetterId { get; set; }
        public Nullable<System.DateTime> IntentToRegisterDeadlineDate { get; set; }
        public Nullable<int> IntentToRegisterDeadlineDecisionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeMember> CommitteeMembers { get; set; }
        public virtual CommonField CommonField { get; set; }
        public virtual CommonField CommonField1 { get; set; }
        public virtual CommonField CommonField2 { get; set; }
        public virtual CommonField CommonField3 { get; set; }
        public virtual CommonField CommonField4 { get; set; }
        public virtual CommonField CommonField5 { get; set; }
        public virtual CommonField CommonField6 { get; set; }
        public virtual CommonField CommonField7 { get; set; }
        public virtual CommonField CommonField8 { get; set; }
        public virtual CommonField CommonField9 { get; set; }
        public virtual CommonField CommonField10 { get; set; }
        public virtual CommonField CommonField11 { get; set; }
        public virtual CommonField CommonField12 { get; set; }
        public virtual CommonField CommonField13 { get; set; }
        public virtual CommonField CommonField14 { get; set; }
        public virtual CommonField CommonField15 { get; set; }
        public virtual CommonField CommonField16 { get; set; }
        public virtual CommonField CommonField17 { get; set; }
        public virtual CommonField CommonField18 { get; set; }
        public virtual CommonField CommonField19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coursework> Courseworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumVitae> CurriculumVitaes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DegreeProgram> DegreePrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduation> Graduations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grant> Grants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Honor> Honors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manuscript> Manuscripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRace> PersonRaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostGraduation> PostGraduations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrevDegree> PrevDegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreviousEmployment> PreviousEmployments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }
    }
}
