//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduate_Class()
        {
            this.Graduate_Semester = new HashSet<Graduate_Semester>();
        }
    
        public int Id { get; set; }
        public int CourseID { get; set; }
        public int GradeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduate_Semester> Graduate_Semester { get; set; }
        public virtual Graduate_Course Graduate_Course { get; set; }
        public virtual Graduate_CommonFields Graduate_CommonFields { get; set; }
    }
}
