//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_Coursework
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public int Year { get; set; }
        public int CourseID { get; set; }
    
        public virtual Graduate_CommonFields Graduate_CommonFields { get; set; }
        public virtual Graduate_Course Graduate_Course { get; set; }
        public virtual Graduate_Student Graduate_Student { get; set; }
    }
}
