//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduate_Student()
        {
            this.Graduate_Coursework = new HashSet<Graduate_Coursework>();
        }
    
        public int Id { get; set; }
        public int StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SchoolEmail { get; set; }
        public string OtherEmail { get; set; }
        public string Phone { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<long> RaceEthnicityBitSum { get; set; }
        public string RaceOther { get; set; }
        public Nullable<int> DegreeProgramId { get; set; }
        public Nullable<int> ConcentrationId { get; set; }
        public Nullable<int> TrackId { get; set; }
        public System.DateTime DegreeStart { get; set; }
        public System.DateTime DegreeEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduate_Coursework> Graduate_Coursework { get; set; }
        public virtual Graduate_CommonFields Graduate_CommonFields { get; set; }
        public virtual Graduate_CommonFields Graduate_CommonFields1 { get; set; }
        public virtual Graduate_CommonFields Graduate_CommonFields2 { get; set; }
        public virtual Graduate_CommonFields Graduate_CommonFields3 { get; set; }
        public virtual Graduate_PrevDegree Graduate_PrevDegree { get; set; }
    }
}
