//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_PrevDegree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduate_PrevDegree()
        {
            this.Graduate_Student = new HashSet<Graduate_Student>();
        }
    
        public int Id { get; set; }
        public int DegreeTypeId { get; set; }
        public string Title { get; set; }
        public decimal GPA { get; set; }
        public string SchoolName { get; set; }
        public string Major { get; set; }
        public string SecondMajor { get; set; }
        public string Minor { get; set; }
        public System.DateTime DateOfAward { get; set; }
    
        public virtual Graduate_CommonFields Graduate_CommonFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduate_Student> Graduate_Student { get; set; }
    }
}
