//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Graduate_CommonFields> Graduate_CommonFields { get; set; }
        public virtual DbSet<Graduate_Course> Graduate_Course { get; set; }
        public virtual DbSet<Graduate_Coursework> Graduate_Coursework { get; set; }
        public virtual DbSet<Graduate_PrevDegree> Graduate_PrevDegree { get; set; }
        public virtual DbSet<Graduate_Student> Graduate_Student { get; set; }
    }
}
