//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTrackingSystem2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_PersonRace
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int RaceID { get; set; }
        public bool Selected { get; set; }
    
        public virtual Graduate_Races Graduate_Races { get; set; }
        public virtual Graduate_Student Graduate_Student { get; set; }
    }
}
